alias ls='ls --color=auto'
alias la='ls -A'
alias ll='ls -x'
alias e='nvim'
alias hss='hugo server --noHTTPCache'
alias td='nvim ~/.TODO'
alias r='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'
