alias ls='ls --color=auto'
alias la='ls -A'
alias ll='ls -x'
alias o='ranger'
alias hss='hugo server --noHTTPCache'
alias td='vim ~/.TODO'
alias r='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'
