#!/bin/sh

# Dependencies
#  slock
#  dmenu

lock_screen(){
	systemctl suspend && slock
}

action_menu(){

	action=$(printf "lock\nrestart\nexit\nshutdown\nreboot" | dmenu -i -c -l 5)

	case $action in
		"lock") lock_screen ;;
		"restart") restartdwm ;;
		"exit") kill -TERM $(pidof dwm) && xdotool key Super_L ;;
		"shutdown") sudo shutdown now ;;
		"reboot") sudo reboot ;;
	esac
}

case $1 in
	"-l") lock_screen ;;
	"-m") action_menu ;;
esac
