#!/bin/sh

# Dependencies
#  slock
#  dmenu

lock_screen(){
	systemctl suspend && slock
}

action_menu(){

	action=$(printf "lock\nexit\nshutdown\nreboot" | dmenu -i -p "powerctl")

	case $action in
		"lock") lock_screen ;;
		"exit") killall dwm ;;
		"shutdown") sudo shutdown now ;;
		"reboot") sudo reboot ;;
	esac
}

case $1 in
	"-l") lock_screen ;;
	"-m") action_menu ;;
esac
