#!/bin/bash
#
# rotate_desktop
#
# Rotates modern Linux desktop screen and input devices to match. Handy for
# convertible notebooks. Call this script from panel launchers, keyboard
# shortcuts, or touch gesture bindings (xSwipe, touchegg, etc.).
#
# Using transformation matrix bits taken from:
#   https://wiki.ubuntu.com/X/InputCoordinateTransformation
#

# Configure these to match your hardware (names taken from `xinput` output).
TOUCHPAD='Elan Touchpad'
TOUCHSCREEN='Elan Touchscreen'
STYLUS_STYLUS='WCOM50C1:00 2D1F:0117 Stylus stylus'
STYLUS='WCOM50C1:00 2D1F:0117 stylus'
STYLUS_ERASER='WCOM50C1:00 2D1F:0117 Stylus eraser'
ERASER='WCOM50C1:00 2D1F:0117 eraser'


if [ -z "$1" ]; then
  echo "Missing orientation."
  echo "Usage: $0 [normal|inverted|left|right] [revert_seconds]"
  echo
  exit 1
fi

function do_rotate
{
  xrandr --output $1 --rotate $2

  TRANSFORM='Coordinate Transformation Matrix'

  case "$2" in
    normal)
      [ ! -z "$TOUCHPAD" ]    && xinput set-prop "$TOUCHPAD"    "$TRANSFORM" 1 0 0 0 1 0 0 0 1
      [ ! -z "$TOUCHSCREEN" ] && xinput set-prop "$TOUCHSCREEN" "$TRANSFORM" 1 0 0 0 1 0 0 0 1
      [ ! -z "$STYLUS_STYLUS" ] && xinput set-prop "$STYLUS_STYLUS" "$TRANSFORM" 1 0 0 0 1 0 0 0 1
      [ ! -z "$STYLUS" ] && xinput set-prop "$STYLUS" "$TRANSFORM" 1 0 0 0 1 0 0 0 1
      [ ! -z "$STYLUS_ERASER" ] && xinput set-prop "$STYLUS_ERASER" "$TRANSFORM" 1 0 0 0 1 0 0 0 1
      [ ! -z "$ERASER" ] && xinput set-prop "$ERASER" "$TRANSFORM" 1 0 0 0 1 0 0 0 1
      ;;
    inverted)
      [ ! -z "$TOUCHPAD" ]    && xinput set-prop "$TOUCHPAD"    "$TRANSFORM" -1 0 1 0 -1 1 0 0 1
      [ ! -z "$TOUCHSCREEN" ] && xinput set-prop "$TOUCHSCREEN" "$TRANSFORM" -1 0 1 0 -1 1 0 0 1
      [ ! -z "$STYLUS_STYLUS" ] && xinput set-prop "$STYLUS_STYLUS" "$TRANSFORM" -1 0 1 0 -1 1 0 0 1
      [ ! -z "$STYLUS" ] && xinput set-prop "$STYLUS" "$TRANSFORM" -1 0 1 0 -1 1 0 0 1
      [ ! -z "$STYLUS_ERASER" ] && xinput set-prop "$STYLUS_ERASER" "$TRANSFORM" -1 0 1 0 -1 1 0 0 1
      [ ! -z "$ERASER" ] && xinput set-prop "$ERASER" "$TRANSFORM" -1 0 1 0 -1 1 0 0 1
      ;;
    left)
      [ ! -z "$TOUCHPAD" ]    && xinput set-prop "$TOUCHPAD"    "$TRANSFORM" 0 -1 1 1 0 0 0 0 1
      [ ! -z "$TOUCHSCREEN" ] && xinput set-prop "$TOUCHSCREEN" "$TRANSFORM" 0 -1 1 1 0 0 0 0 1
      [ ! -z "$STYLUS_STYLUS" ] && xinput set-prop "$STYLUS_STYLUS" "$TRANSFORM" 0 -1 1 1 0 0 0 0 1
      [ ! -z "$STYLUS" ] && xinput set-prop "$STYLUS" "$TRANSFORM" 0 -1 1 1 0 0 0 0 1
      [ ! -z "$STYLUS_ERASER" ] && xinput set-prop "$STYLUS_ERASER" "$TRANSFORM" 0 -1 1 1 0 0 0 0 1
      [ ! -z "$ERASER" ] && xinput set-prop "$ERASER" "$TRANSFORM" 0 -1 1 1 0 0 0 0 1
      ;;
    right)
      [ ! -z "$TOUCHPAD" ]    && xinput set-prop "$TOUCHPAD"    "$TRANSFORM" 0 1 0 -1 0 1 0 0 1
      [ ! -z "$TOUCHSCREEN" ] && xinput set-prop "$TOUCHSCREEN" "$TRANSFORM" 0 1 0 -1 0 1 0 0 1
      [ ! -z "$STYLUS_STYLUS" ] && xinput set-prop "$STYLUS_STYLUS" "$TRANSFORM" 0 1 0 -1 0 1 0 0 1
      [ ! -z "$STYLUS" ] && xinput set-prop "$STYLUS" "$TRANSFORM" 0 1 0 -1 0 1 0 0 1
      [ ! -z "$STYLUS_ERASER" ] && xinput set-prop "$STYLUS_ERASER" "$TRANSFORM" 0 1 0 -1 0 1 0 0 1
      [ ! -z "$ERASER" ] && xinput set-prop "$ERASER" "$TRANSFORM" 0 1 0 -1 0 1 0 0 1
      ;;
  esac
}

XDISPLAY=`xrandr --current | grep primary | sed -e 's/ .*//g'`
XROT=`xrandr --current --verbose | grep primary | egrep -o ' (normal|left|inverted|right) '`

do_rotate $XDISPLAY $1

if [ ! -z "$2" ]; then
  sleep $2
  do_rotate $XDISPLAY $XROT
  exit 0
fi

