#!/bin/sh

# Dependencies
#
#

case $BUTTON in
	# On left click
	1) ;;
	# On middle click
	2) ;;
	# On right click
	3) ;;
	# On scroll up
	4) ;;
	# On scroll down
	5) ;;
	# On Shift+left click, open this file
	6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac
