#!/bin/sh

# Dependencies
#  vim
#  xdg-open
#  pdflatex

name=$(echo $1 | sed "s/\..*$//")

open_texfile(){
	pdflatex "$name.tex" && zathura "$name.pdf" & $EDITOR "$name.tex"
}
if [ -f "$name.tex" ]; then
  open_texfile
else
  cp "$HOME/.scripts/template.tex" "$name.tex" && open_texfile
fi
